#
# ~/.bashrc
#

# If not running interactively, don't do anything
[[ $- != *i* ]] && return

PS1='\n[\[\033[1;34m\]\w\[\033[1;37m\]] \[\033[1;31m\]$(git branch --show-current 2> /dev/null)\n\[\033[1;36m\]\h \[\033[1;32m\]⊨\[\033[00m\] '

export EDITOR="nvim"
export TERMINAL="kitty"

alias ..='cd .. && ls -la'
alias ...='cd ../.. && ls -la'
alias -- -='cd -'
alias ls='ls --color=auto'
alias la='ls -lvah'
alias ll='ls -lvh'
alias vi=$EDITOR
alias py='python'
alias cd='z'
alias cat='bat'
alias htop='btop'
alias open='xdg-open'
alias vit='vi -c "Git log | only | vert Git"'
alias kssh='kitten +kitten ssh'
alias vpnup='sudo systemctl start wg-quick-wg0'
alias vpndown='sudo systemctl stop wg-quick-wg0'
alias nixconf='cd ~/dots/ && vi ~/dots/hosts/buggy/configuration.nix && cd -'
alias nixsw='nh os switch ~/dots/#buggy'
alias nixservsw='nh os switch ~/dots/#wapol --target-host brian@wapol'

eval "$(fzf --bash)"
eval "$(zoxide init bash)"
eval "$(direnv hook bash)"

flakify() {
  if [ ! -e flake.nix ]; then
    nix flake new -t git+https://codeberg.org/bkle/dots .
  fi

  if [ ! -e .envrc ]; then
    echo "use flake" > .envrc
    direnv allow
  fi

  vi flake.nix +/cowsay
}

unfree() {
    NIXPKGS_ALLOW_UNFREE=1 $@ --impure
}

